'''
    RUNNING INSTRUCTIONS:
    $ python3 random_string_generator.py <file_name> <length_of_string>

    PARAMETER DESCRIPTION:
    <file_name> : This is the filename that you would like to give to the random string file that is being generated.
    <length_of_string> : This parameter sets the max size of string generated by Random String Generator.

    EXAMPLE:
    $ python3 random_string_generator.py input.txt 1000000000

    This will generate file named "input.txt" which has string of length 1000000000. This file will be around 1GB in size. 
    You can play around with the values to generate different files.
'''

import random
import string
import sys
import time

string_size = 10_000_000
BUFFER_SIZE = 100_000

default_seed = 69420
file_name = "bigRandomString.txt"
char_list = list(string.ascii_letters) + list(string.digits)

if __name__ == '__main__':
    try:
        file_name = str(sys.argv[1])
    except:
        pass

    try:
        string_size = int(sys.argv[2])
    except:
        pass

    random.seed(default_seed)

    start_time = time.time()

    o_file = open(file_name, "w")

    written_count = 0
    for _ in range(string_size // BUFFER_SIZE):
        buffer = ''.join(random.choices(char_list, k=BUFFER_SIZE))
        written_count += len(buffer)
        o_file.write(buffer)

    buffer = ''.join(random.choices(char_list, k=string_size % BUFFER_SIZE))
    written_count += len(buffer)
    o_file.write(buffer)

    o_file.close()

    end_time = time.time()
    print("String Size Written : ", written_count)
    print("Time taken : ", end_time - start_time)
